/**
 * EML draft generator
 * ────────────────────
 * Generates an RFC 2822-compliant `.eml` file from a structured agent answer
 * or research brief. The result can be opened directly in Outlook, Apple Mail,
 * Thunderbird, and most desktop email clients — the user gets a pre-populated
 * draft they can review and send with zero copy-paste friction.
 *
 * No external dependencies; builds plain text + HTML multipart/alternative so
 * the email renders in HTML-capable clients and falls back to plaintext
 * gracefully.
 */

export interface EmlDraftInput {
  subject: string
  /** Primary prose body — may contain Markdown-style bullets. Rendered as
   *  plain-text and converted to a simple HTML structure in the HTML part. */
  body: string
  /** Key-point summary bullets shown above the body in HTML view. */
  keyPoints?: string[]
  /** Cited sources appended as a footer. */
  citations?: string[]
  /** Sender display name shown in From: header (no email address). */
  fromName?: string
  /** Optional To: address pre-populated in the draft. */
  toAddress?: string
  /** Ticker or entity the email is about — used in footer attribution. */
  ticker?: string
  /** ISO date string or label for the "as of" footer. */
  asOf?: string
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function markdownToSimpleHtml(text: string): string {
  return text
    .split('\n')
    .map((line) => {
      const t = line.trim()
      if (!t) return '<br>'
      // Bullet points
      if (t.startsWith('- ') || t.startsWith('• ') || t.startsWith('* ')) {
        return `<li>${escapeHtml(t.slice(2))}</li>`
      }
      // Bold **text**
      const bolded = escapeHtml(t).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      return `<p style="margin:4px 0">${bolded}</p>`
    })
    .join('\n')
}

function buildPlainText(input: EmlDraftInput): string {
  const lines: string[] = []

  if (input.ticker) {
    lines.push(`${input.ticker}${input.asOf ? ` — ${input.asOf}` : ''}`)
    lines.push('─'.repeat(60))
    lines.push('')
  }

  if (input.keyPoints && input.keyPoints.length > 0) {
    lines.push('KEY POINTS')
    lines.push('')
    for (const kp of input.keyPoints) {
      lines.push(`  • ${kp}`)
    }
    lines.push('')
    lines.push('─'.repeat(60))
    lines.push('')
  }

  lines.push(input.body)

  if (input.citations && input.citations.length > 0) {
    lines.push('')
    lines.push('─'.repeat(60))
    lines.push('SOURCES')
    lines.push('')
    input.citations.forEach((c, i) => {
      lines.push(`  [${i + 1}] ${c}`)
    })
  }

  lines.push('')
  lines.push('─'.repeat(60))
  lines.push('Generated by Finsyt Research · finsyt.com')

  return lines.join('\r\n')
}

function buildHtml(input: EmlDraftInput): string {
  const ticker = input.ticker ? escapeHtml(input.ticker) : ''
  const asOf = input.asOf ? escapeHtml(input.asOf) : ''

  const keyPointsHtml = input.keyPoints && input.keyPoints.length > 0
    ? `<div style="background:#EAF1FF;border-left:3px solid #4F7CFF;padding:12px 16px;margin-bottom:18px;border-radius:0 6px 6px 0">
        <p style="margin:0 0 8px;font-weight:700;color:#0B1B3D;font-size:13px;letter-spacing:.5px;text-transform:uppercase">Key Points</p>
        <ul style="margin:0;padding-left:18px;color:#0E1A33;font-size:14px;line-height:1.7">
          ${input.keyPoints.map((kp) => `<li>${escapeHtml(kp)}</li>`).join('\n          ')}
        </ul>
      </div>`
    : ''

  const bodyHtml = markdownToSimpleHtml(input.body)
  const isListBody = bodyHtml.includes('<li>')
  const wrappedBody = isListBody
    ? `<ul style="padding-left:20px;color:#4A5568;line-height:1.7">${bodyHtml}</ul>`
    : `<div style="color:#4A5568;font-size:14px;line-height:1.75">${bodyHtml}</div>`

  const citationsHtml = input.citations && input.citations.length > 0
    ? `<div style="margin-top:24px;padding-top:16px;border-top:1px solid #E2E8F0">
        <p style="margin:0 0 8px;font-weight:600;color:#6B7280;font-size:12px;letter-spacing:.5px;text-transform:uppercase">Sources</p>
        <ol style="margin:0;padding-left:18px;color:#6B7280;font-size:12px;line-height:1.7">
          ${input.citations.map((c) => `<li>${escapeHtml(c)}</li>`).join('\n          ')}
        </ol>
      </div>`
    : ''

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F7F9FC;font-family:Inter,Arial,sans-serif">
  <table role="presentation" style="width:100%;background:#F7F9FC"><tr><td style="padding:32px 16px">
    <div style="max-width:640px;margin:0 auto;background:#FFFFFF;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,.08);overflow:hidden">

      <!-- Header -->
      <div style="background:#0B1B3D;padding:20px 28px 16px">
        <p style="margin:0;color:#8FB3FF;font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase">Finsyt Research</p>
        ${ticker ? `<p style="margin:6px 0 0;color:#FFFFFF;font-size:20px;font-weight:800;letter-spacing:-.5px">${ticker}${asOf ? `<span style="font-size:13px;font-weight:400;color:#D7E0F5;margin-left:12px">${asOf}</span>` : ''}</p>` : ''}
      </div>
      <div style="height:3px;background:#4F7CFF"></div>

      <!-- Body -->
      <div style="padding:24px 28px 20px">
        ${keyPointsHtml}
        ${wrappedBody}
        ${citationsHtml}
      </div>

      <!-- Footer -->
      <div style="background:#F7F9FC;padding:14px 28px;border-top:1px solid #E2E8F0">
        <p style="margin:0;color:#6B7280;font-size:11px">Generated by <strong style="color:#0B1B3D">Finsyt</strong> · <a href="https://finsyt.com" style="color:#4F7CFF;text-decoration:none">finsyt.com</a>${asOf ? ` · ${asOf}` : ''}</p>
      </div>
    </div>
  </td></tr></table>
</body>
</html>`
}

function rfc2822Date(d = new Date()): string {
  return d.toUTCString().replace('GMT', '+0000')
}

function quotedPrintable(s: string): string {
  // Very simple QP encoder — only handles ASCII + common characters
  // used in our generated text (no binary needed here).
  return s
    .split('\r\n')
    .map((line) => {
      let encoded = ''
      for (let i = 0; i < line.length; i++) {
        const c = line.charCodeAt(i)
        if (c > 126 || (c < 32 && c !== 9)) {
          encoded += `=${c.toString(16).toUpperCase().padStart(2, '0')}`
        } else {
          encoded += line[i]
        }
      }
      return encoded
    })
    .join('\r\n')
}

/**
 * Build a complete RFC 2822 `.eml` string ready to be streamed as a file.
 *
 * The MIME structure is `multipart/alternative` so clients that can render
 * HTML show the branded layout; clients that only read plaintext see the
 * structured text version.
 */
export function buildEml(input: EmlDraftInput): string {
  const boundary = `finsyt_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`
  const from = input.fromName
    ? `"${input.fromName.replace(/"/g, '')}" <research@finsyt.com>`
    : 'Finsyt Research <research@finsyt.com>'
  const to = input.toAddress ? input.toAddress : ''

  const plainPart = buildPlainText(input)
  const htmlPart  = buildHtml(input)

  const lines: string[] = [
    `MIME-Version: 1.0`,
    `Date: ${rfc2822Date()}`,
    `From: ${from}`,
    ...(to ? [`To: ${to}`] : []),
    `Subject: ${input.subject}`,
    `Content-Type: multipart/alternative; boundary="${boundary}"`,
    `X-Generator: Finsyt-Research-Agent/1.0`,
    ``,
    `--${boundary}`,
    `Content-Type: text/plain; charset=UTF-8`,
    `Content-Transfer-Encoding: quoted-printable`,
    ``,
    quotedPrintable(plainPart),
    ``,
    `--${boundary}`,
    `Content-Type: text/html; charset=UTF-8`,
    `Content-Transfer-Encoding: quoted-printable`,
    ``,
    quotedPrintable(htmlPart),
    ``,
    `--${boundary}--`,
  ]

  return lines.join('\r\n')
}

/**
 * Convenience wrapper: returns a Buffer (UTF-8) of the EML content and a
 * safe filename derived from the subject.
 */
export function buildEmlBuffer(input: EmlDraftInput): { buffer: Buffer; filename: string } {
  const eml = buildEml(input)
  const safe = (input.subject || 'Research Email')
    .replace(/[^\w\s\-().]/g, '')
    .trim()
    .slice(0, 80)
  const filename = `${safe}.eml`
  return { buffer: Buffer.from(eml, 'utf-8'), filename }
}
