/**
 * Matrix → PPTX exporter
 * ─────────────────────────────
 * Renders a Hebbia-class research matrix (rows × columns of agent answers)
 * into a Finsyt-branded slide deck. The first slide is a title + summary
 * card; subsequent slides render one row per slide with a 2-column table of
 * (column prompt → cell answer + citations) so every cell stays human-
 * legible at presentation scale.
 *
 * Brand tokens are imported from `investment-memo-pptx.ts` so the matrix
 * deck visually matches the rest of the Finsyt PPTX surface.
 */
import PptxGenJS from 'pptxgenjs'
import { BRAND } from './investment-memo-pptx'

export interface MatrixExportRow {
  id: string
  label: string
  ticker?: string
}

export interface MatrixExportColumn {
  id: string
  label: string
  prompt: string
}

export interface MatrixExportCitation {
  label: string
  summary?: string
  href?: string
  type?: string
}

export interface MatrixExportCell {
  state: string
  text?: string
  error?: string
  citations?: MatrixExportCitation[]
  ms?: number
  provider?: string
}

export interface MatrixExportData {
  name: string
  description?: string
  generatedAt: string // ISO
  rows: MatrixExportRow[]
  columns: MatrixExportColumn[]
  cells: Record<string, MatrixExportCell>
}

const SLIDE_W = 13.333
const SLIDE_H = 7.5

function header(slide: PptxGenJS.Slide, title: string, subtitle?: string) {
  slide.addShape('rect', { x: 0, y: 0, w: SLIDE_W, h: 0.55, fill: { color: BRAND.navy }, line: { color: BRAND.navy } })
  slide.addText(title, {
    x: 0.4, y: 0.06, w: SLIDE_W - 0.8, h: 0.42,
    fontFace: 'Inter', fontSize: 16, bold: true, color: 'FFFFFF', valign: 'middle',
  })
  if (subtitle) {
    slide.addText(subtitle, {
      x: 0.4, y: 0.06, w: SLIDE_W - 0.8, h: 0.42,
      fontFace: 'Inter', fontSize: 11, color: BRAND.accentDim, align: 'right', valign: 'middle',
    })
  }
}

function footer(slide: PptxGenJS.Slide, pageNum: number, total: number) {
  slide.addText('Generated by Finsyt Matrix · finsyt.app', {
    x: 0.4, y: SLIDE_H - 0.4, w: 8, h: 0.3,
    fontFace: 'Inter', fontSize: 9, color: BRAND.muted,
  })
  slide.addText(`${pageNum} / ${total}`, {
    x: SLIDE_W - 1.2, y: SLIDE_H - 0.4, w: 0.8, h: 0.3,
    fontFace: 'Inter', fontSize: 9, color: BRAND.muted, align: 'right',
  })
}

function buildTitleSlide(pptx: PptxGenJS, data: MatrixExportData, total: number) {
  const s = pptx.addSlide()
  header(s, 'Finsyt Matrix', new Date(data.generatedAt).toUTCString())
  s.addText(data.name, {
    x: 0.6, y: 1.4, w: SLIDE_W - 1.2, h: 1.0,
    fontFace: 'Inter', fontSize: 32, bold: true, color: BRAND.ink,
  })
  if (data.description) {
    s.addText(data.description, {
      x: 0.6, y: 2.5, w: SLIDE_W - 1.2, h: 0.8,
      fontFace: 'Inter', fontSize: 14, color: BRAND.body,
    })
  }
  s.addText(
    [
      { text: `${data.rows.length}`, options: { bold: true, color: BRAND.accent, fontSize: 28 } },
      { text: '   entities  ·  ', options: { color: BRAND.muted, fontSize: 14 } },
      { text: `${data.columns.length}`, options: { bold: true, color: BRAND.accent, fontSize: 28 } },
      { text: '   prompts  ·  ', options: { color: BRAND.muted, fontSize: 14 } },
      { text: `${countCompletedCells(data)}`, options: { bold: true, color: BRAND.positive, fontSize: 28 } },
      { text: '   answers', options: { color: BRAND.muted, fontSize: 14 } },
    ],
    { x: 0.6, y: 4.0, w: SLIDE_W - 1.2, h: 0.8, fontFace: 'Inter' },
  )
  s.addShape('rect', { x: 0.6, y: 5.2, w: 1.6, h: 0.06, fill: { color: BRAND.accent }, line: { color: BRAND.accent } })
  s.addText('Each subsequent slide presents one entity row with every prompt-answer pair.', {
    x: 0.6, y: 5.4, w: SLIDE_W - 1.2, h: 0.5,
    fontFace: 'Inter', fontSize: 11, color: BRAND.muted, italic: true,
  })
  footer(s, 1, total)
}

function countCompletedCells(data: MatrixExportData): number {
  let n = 0
  for (const r of data.rows) for (const c of data.columns) {
    const cell = data.cells[`${r.id}.${c.id}`]
    if (cell?.state === 'done') n++
  }
  return n
}

function buildEntitySlide(
  pptx: PptxGenJS,
  data: MatrixExportData,
  row: MatrixExportRow,
  page: number,
  total: number,
) {
  const s = pptx.addSlide()
  const subtitle = row.ticker ? row.ticker : ''
  header(s, row.label, subtitle)

  const columns = data.columns
  // Build a table: prompt | answer | citations.
  const tableData: PptxGenJS.TableRow[] = [[
    { text: 'Prompt',    options: { bold: true, color: 'FFFFFF', fill: { color: BRAND.navy }, fontFace: 'Inter', fontSize: 10 } },
    { text: 'Answer',    options: { bold: true, color: 'FFFFFF', fill: { color: BRAND.navy }, fontFace: 'Inter', fontSize: 10 } },
    { text: 'Citations', options: { bold: true, color: 'FFFFFF', fill: { color: BRAND.navy }, fontFace: 'Inter', fontSize: 10 } },
  ]]

  for (const col of columns) {
    const cell = data.cells[`${row.id}.${col.id}`]
    const answer = cell?.state === 'done' ? (cell.text || '—') : (cell?.state === 'error' ? `Error: ${cell.text || 'failed'}` : '— not run')
    const cites = (cell?.citations || []).map((c, i) => `[${i + 1}] ${c.label}`).join('\n') || '—'
    tableData.push([
      { text: `${col.label}\n`, options: { bold: true, color: BRAND.ink, fontFace: 'Inter', fontSize: 10 } },
      { text: answer.slice(0, 1200), options: { color: BRAND.body, fontFace: 'Inter', fontSize: 9 } },
      { text: cites.slice(0, 600), options: { color: BRAND.accent, fontFace: 'Inter', fontSize: 9 } },
    ])
  }

  s.addTable(tableData, {
    x: 0.4, y: 0.8, w: SLIDE_W - 0.8, h: SLIDE_H - 1.4,
    colW: [3.0, 6.5, 3.0],
    border: { type: 'solid', color: BRAND.divider, pt: 0.5 },
    fontFace: 'Inter',
    valign: 'top',
    autoPage: true,
    autoPageRepeatHeader: true,
    autoPageCharWeight: -0.2,
    autoPageLineWeight: 0.0,
  })
  footer(s, page, total)
}

export async function buildMatrixPptx(data: MatrixExportData): Promise<Buffer> {
  const pptx = new PptxGenJS()
  pptx.layout = 'LAYOUT_WIDE'
  pptx.author = 'Finsyt'
  pptx.company = 'Finsyt'
  pptx.title = `Matrix · ${data.name}`

  const total = 1 + data.rows.length
  buildTitleSlide(pptx, data, total)
  data.rows.forEach((row, i) => buildEntitySlide(pptx, data, row, i + 2, total))

  const out = await pptx.write({ outputType: 'nodebuffer' })
  if (typeof out === 'string') return Buffer.from(out, 'binary')
  if (out instanceof Uint8Array) return Buffer.from(out)
  return Buffer.from(new Uint8Array(out as ArrayBuffer))
}

// CSV helper: emit one row per (entity, prompt) pair so analysts can pivot
// in Excel/Sheets. Strings are double-quoted with escaped embedded quotes.
function csvEscape(s: string): string {
  if (s == null) return ''
  const needs = /[",\n\r]/.test(s)
  return needs ? `"${s.replace(/"/g, '""')}"` : s
}

// Placeholder shown in CSV cells whose run hasn't completed yet. Mirrors
// the convention from the deck export so analysts opening the spreadsheet
// can tell at a glance which cells are simply not yet computed (vs. an
// intentionally blank answer). Errored cells get their own marker so
// nothing is silently swallowed.
const PENDING_PLACEHOLDER = '(pending — not yet run)'

function csvAnswerText(cell: MatrixExportCell | undefined): string {
  if (!cell) return PENDING_PLACEHOLDER
  if (cell.state === 'done') return cell.text || ''
  if (cell.state === 'error') return cell.error ? `(error — ${cell.error})` : '(error)'
  // 'idle' | 'queued' | 'running' | undefined — treat as not-yet-run so the
  // CSV is honest about what's been computed.
  return PENDING_PLACEHOLDER
}

export function buildMatrixCsv(data: MatrixExportData): string {
  const lines: string[] = []
  lines.push(['entity', 'ticker', 'column', 'prompt', 'state', 'answer', 'provider', 'citations'].join(','))
  for (const r of data.rows) {
    for (const c of data.columns) {
      const cell = data.cells[`${r.id}.${c.id}`]
      const cites = (cell?.citations || []).map((x, i) => `[${i + 1}] ${x.label}${x.href ? ` (${x.href})` : ''}`).join(' | ')
      lines.push([
        csvEscape(r.label),
        csvEscape(r.ticker || ''),
        csvEscape(c.label),
        csvEscape(c.prompt),
        csvEscape(cell?.state || 'idle'),
        csvEscape(csvAnswerText(cell)),
        csvEscape(cell?.provider || ''),
        csvEscape(cites),
      ].join(','))
    }
  }
  return lines.join('\n')
}
