import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth-server'
import { getMemo } from '@/lib/memo-store'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

/**
 * GET /api/copilot/memo/[fileId]
 *
 * Streams a previously-generated investment memo PPTX back as a
 * download. Auth-gated and ownership-checked: a memo generated by user
 * A cannot be downloaded by user B in another session.
 */
export async function GET(req: NextRequest, ctx: { params: Promise<{ fileId: string }> }) {
  const { userId } = await auth()
  if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { fileId } = await ctx.params
  const memo = await getMemo(fileId)
  if (!memo) {
    return NextResponse.json({ error: 'Memo not found or expired. Please regenerate.' }, { status: 404 })
  }
  if (memo.userId && memo.userId !== userId) {
    return NextResponse.json({ error: 'You do not have access to this memo.' }, { status: 403 })
  }

  // Build a Uint8Array body so Next.js streams a real binary response
  const body = new Uint8Array(memo.buffer)
  return new NextResponse(body, {
    status: 200,
    headers: {
      'Content-Type': memo.contentType,
      'Content-Disposition': `attachment; filename="${memo.filename.replace(/"/g, '')}"`,
      'Content-Length': String(memo.bytes),
      'Cache-Control': 'private, no-store',
    },
  })
}
